#!/usr/bin/env perl

# Copyright (C) 2015-2017 Yoann Le Garff, Nicolas Boquet and Yann Le Bras
# navel-hub is licensed under the Apache License, Version 2.0

#-> initialization

use Navel::Base;

use FindBin;

BEGIN {
    unshift @INC, $FindBin::Bin . '/../lib';
}

use Mojolicious::Commands;

#-> main

Mojolicious::Commands->start_app('Navel::Hub');

#-> END

__END__

=pod

=encoding utf8

=head1 NAME

navel-hub - Run Navel::Hub

=head1 COPYRIGHT

Copyright (C) 2015-2017 Yoann Le Garff, Nicolas Boquet and Yann Le Bras

=head1 LICENSE

navel-hub is licensed under the Apache License, Version 2.0

=cut
